SELECT ROUND(((SUM(LENGTH) + (CNT * 10)) / (COUNT(LENGTH) + CNT)), 2) AS AVERAGE_LENGTH
FROM (
    SELECT COUNT(*) AS CNT
    FROM FISH_INFO 
    WHERE LENGTH IS NULL
) A, FISH_INFO
WHERE LENGTH IS NOT NULL;

